### ISSUE TITLE
[Challenge] Sum of Squares

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#11]
# Sum of Squares

Given a positive integer `n`, find the smallest number of squared integers which sum to `n` (i.e. `n = x² + y²` should yield `2`).

## Business Rules/Errata

- Any attempt to provide non-integer, non-positive input should return an error.
- Return only the count of squared integers that sum to `n`, not the list of integers.
- Remember that 1² = 1.

## Examples

```
count_squared_addends(13);  // 2
count_squared_addends(27);  // 3
```

- For `n` = 13: 3² + 2² = 9 + 4 = 13
- For `n` = 27: 
    - 3² + 3² + 3² =   9 + 9 + 9 = 27
    - 5² + 1² + 1² = 25 + 1 + 1 = 27

**Comment by xanderyzwich** [comment]
I think that we can do a quick start of this one in light of #28 . Build 'change' from squares less than the given number, and then reuse that algorithm with tweaks that an item can be reused.

**Comment by parhaml** [comment]
I think this one should stand on it's own. Hopefully we'll have other attendees who weren't at previous dojo and would need to approach this problem fresh.
