### ISSUE TITLE
[Hacktoberfest] Bash | Intervening Verbiage

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#174]
# Participation

All Hacktoberfest solutions should be provably correct. That is, solution submissions should either include the unit tests from the original challenge (implemented in your language of choice) or at least print out the expected answers when run by the maintainers. Solutions that do not meet these criteria may be rejected, or flagged as 'invalid' or 'spam' in egregious cases. This can result in your PR not counting towards your Hacktoberfest participation or becoming ineligible to participate in Hacktoberfest. Violations of our [Code of Conduct](https://github.com/codeconnector/CodingDojo/blob/main/CODE_OF_CONDUCT.md) will be reported, and will also render you ineligible to participate in Hacktoberfest. Please be respectful of the maintainers' and other participants' time by doing your best to submit real solutions to the puzzles. Thanks, and welcome to our learning community!

# Challenge

[Intervening Verbiage](https://github.com/codeconnector/CodingDojo/blob/main/challenges/2021-04-06-intervening-verbiage/challenge.md)

# Language

Complete this challenge using a Bash/Shell script.

# Approach

Shell scripts expect to take a string as input and echo to stdout as output. For added credibility, prove your solution with unit tests. One option for unit testing Bash scripts is [bats](https://github.com/bats-core/bats-core).

**Comment by shankarjp** [comment]
I think I can fix this issue, can you assign this to me?

**Comment by williycole** [comment]
I'll knock this one out later today.
