### ISSUE TITLE
[Hacktoberfest] Java | Single and Ready to Mingle

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#175]
# Participation

All Hacktoberfest solutions should be provably correct. That is, solution submissions should either include the unit tests from the original challenge (implemented in your language of choice) or at least print out the expected answers when run by the maintainers. Solutions that do not meet these criteria may be rejected, or flagged as 'invalid' or 'spam' in egregious cases. This can result in your PR not counting towards your Hacktoberfest participation or becoming ineligible to participate in Hacktoberfest. Violations of our [Code of Conduct](https://github.com/codeconnector/CodingDojo/blob/main/CODE_OF_CONDUCT.md) will be reported, and will also render you ineligible to participate in Hacktoberfest. Please be respectful of the maintainers' and other participants' time by doing your best to submit real solutions to the puzzles. Thanks, and welcome to our learning community!

# Challenge

[Single and Ready to Mingle](https://github.com/codeconnector/CodingDojo/blob/main/challenges/2021-04-13-single-and-ready-to-mingle/challenge.md)

# Language

Java

# Approach

For added credibility, prove your solution with unit tests. Check out any of our Java-based challenges for an IDE-agnostic testing setup. or use the built-in tools from your favorite IDE.

**Comment by neeraj15022001** [comment]
can i try this one ?

**Comment by ericwburden** [comment]
Go for it. For details on submitting a solution, check out: https://github.com/codeconnector/CodingDojo/wiki#solutions

Welcome to the Coding Dojo, a part of the [CodeConnector](https://codeconnector.io/) community!
