### ISSUE TITLE
[Hacktoberfest] Ruby | Sum Arrays

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#177]
# Participation

All Hacktoberfest solutions should be provably correct. That is, solution submissions should either include the unit tests from the original challenge (implemented in your language of choice) or at least print out the expected answers when run by the maintainers. Solutions that do not meet these criteria may be rejected, or flagged as 'invalid' or 'spam' in egregious cases. This can result in your PR not counting towards your Hacktoberfest participation or becoming ineligible to participate in Hacktoberfest. Violations of our [Code of Conduct](https://github.com/codeconnector/CodingDojo/blob/main/CODE_OF_CONDUCT.md) will be reported, and will also render you ineligible to participate in Hacktoberfest. Please be respectful of the maintainers' and other participants' time by doing your best to submit real solutions to the puzzles. Thanks, and welcome to our learning community!

# Challenge

[Sum Arrays](https://github.com/codeconnector/CodingDojo/blob/main/challenges/2021-04-27-sum-arrays/challenge.md)

# Language

This challenge was originally set up for Ruby, but it looks like a Ruby solution was never submitted! Yikes! Solve this challenge in Ruby and fix that oversight for us, please.

# Approach

Use the original unit tests!

**Comment by mohdarif8299** [comment]
Can I work on this?

**Comment by ericwburden** [comment]
Go for it.

**Comment by mohdarif8299** [comment]
> Go for it.

Unable to  push code. Access denied.

**Comment by xanderyzwich** [comment]
> Unable to push code. Access denied.
@mohdarif8299 please see the [wiki](https://github.com/codeconnector/CodingDojo/wiki) for instructions to contribute. You must fork the repository and make your changes in that fork. you will then submit a pull request with the changes.

**Comment by ericwburden** [comment]
https://dev.to/adamreidelbach/open-source-git-workflow-an-overview-2oo2

This should help, too.
