### ISSUE TITLE
[Hacktoberfest] Java | Simple 2D Iterator

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#181]
# Participation

All Hacktoberfest solutions should be provably correct. That is, solution submissions should either include the unit tests from the original challenge (implemented in your language of choice) or at least print out the expected answers when run by the maintainers. Solutions that do not meet these criteria may be rejected, or flagged as 'invalid' or 'spam' in egregious cases. This can result in your PR not counting towards your Hacktoberfest participation or becoming ineligible to participate in Hacktoberfest. Violations of our [Code of Conduct](https://github.com/codeconnector/CodingDojo/blob/main/CODE_OF_CONDUCT.md) will be reported, and will also render you ineligible to participate in Hacktoberfest. Please be respectful of the maintainers' and other participants' time by doing your best to submit real solutions to the puzzles. Thanks, and welcome to our learning community!

# Challenge

[Simple 2D Iterator](https://github.com/codeconnector/CodingDojo/blob/main/challenges/2021-06-08-simple-2d-iterator/challenge.md)

# Language

Lots of Java in the repo already, add some more! Solve this challenge using Java.

# Approach

Check out some of our Java-based challenges for an IDE-agnostic unit-testing setup, or use the tools built in to your favorite IDE.

**Comment by neeraj15022001** [comment]
can i try this one ?

**Comment by drkennetz** [comment]
@neeraj15022001 , Hi anybody can solve these - please refer to:
https://github.com/codeconnector/CodingDojo/wiki#solutions

For details on how to submit solutions to this repo. Thanks!
