### ISSUE TITLE
Add  Meetup info to README

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/CodingDojo#187]
To help with people learning about our repository through Hacktoberfest, we should include a link to the meetup page for people to join us in the future.

**Comment by xanderyzwich** [comment]
Link to the organization: https://www.meetup.com/memphis-technology-user-groups

**Comment by YushChaudhary** [comment]
is it open. can you assign me this?

**Comment by SGR007** [comment]
Hey, can you assign me this

**Comment by xanderyzwich** [comment]
@SGR007 Hi anybody can solve these - please refer to:
https://github.com/codeconnector/CodingDojo/wiki#solutions

For details on how to submit solutions to this repo. Thanks!

**Comment by ericwburden** [comment]
Closed by #189
