### ISSUE TITLE
Update Hacktoberfest template for Issue reference

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/CodingDojo#188]
PR's should reference the issue number for ease of review and closure.

**Comment by SubhamChoudhury** [comment]
Hi, can I work on this issue?

**Comment by ericwburden** [comment]
Go for it.

**Comment by manojkrishnak** [comment]
Hi, can I take this?

**Comment by xanderyzwich** [comment]
@manojkrishnak it appears that someone else has already opened a pull request for this. Please look at our other open issues to find something that you can work on.
