### ISSUE TITLE
[Challenge] Simple 2D Iterator

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#25]
# Simple 2D Iterator

Implement a class (or struct, or object) representing a 2-dimensional iterator. This class should be initialized with a 2-dimensional (nested) array, and should implement two methods:

- `next()` returns the next element in the array of arrays
- `has_next()` returns true/false indicating whether the iterator still has elements left

## Business Rules/Errata

- ***Data Structure Required: 2D Array***
- Your class will need a constructor method (or other strategy) to accept a 2-dimensional array and produce an instance of your class.
- You should not `flatten` or otherwise copy data out of the 2D array into another data structure.
- If you call `next()` on your class, and there are no elements left to return, return `null` (or some other indicator that the iterator has been exhausted).

### Example 1

```
instance = new NestedIterator([[1, 2], [3], [], [4, 5, 6]]);
instance.next()  // 1
instance.next()  // 2
instance.next()  // 3
instance.has_next()  // true
instance.next()  // 4
instance.next()  // 5
instance.next()  // 6
instance.has_next()  // false
instance.next()  // NULL
```

### Example 2

```
instance = new NestedIterator([[9], [1, 7, 5], [2, 9], []]);
instance.next()  // 9
instance.next()  // 1
instance.next()  // 7
instance.has_next()  // true
instance.next()  // 5
instance.next()  // 6
instance.next()  // 9
instance.has_next()  // false
instance.next()  // NULL
```

**Comment by xanderyzwich** [comment]
@ericwburden I'd like to see an example of the proposed functionality where the numbers are not in order.

**Comment by ericwburden** [comment]
Also updated the examples to make it clearer that there's an object/class involved.

**Comment by xanderyzwich** [comment]
Thanks @ericwburden that makes it a lot easier to understand what needs to happen. I like this, and think it is achievable.
