### ISSUE TITLE
[Challenge] Non-Constructible Change

### ISSUE THREAD

**Issue by drkennetz** [codeconnector/CodingDojo#28]
# Non-Constructible Change

Given an array of sorted positive integers representing the values of coins in your possession, write a function that returns the minimum amount of change (the minimum sum of money) that you **cannot** create.

## Business Rules/Errata

- You can assume that the input will be a list or array of  **sorted** integers.
- The given coins can have any positive integer value, they do not have to correspond to real coin values (for example, we could have a coin worth 3).
- The coins aren't necessarily unique (you could have 7 coins worth 1, 2 coins worth 3, etc.
- Extra challenge: Complete this challenge in linear time and constant space.

## Examples

```
coins = [1]
nonConstructibleChange(coins) // 2

coins = [1, 1, 1, 1, 1]
nonConstructibleChange(coins) // 6 

coins = [1, 1, 2, 3, 5, 7, 22]
nonConstructibleChange(coins) // 20

coins = [1, 1, 4, 5, 6, 8, 9]
nonConstructibleChange(coins) // 3

coins = [1, 1, 1, 1, 5, 10, 15, 20, 100]
nonConstructibleChange(coins) // 55
```

**Comment by xanderyzwich** [comment]
This is a perfect level of complexity, I think!
