### ISSUE TITLE
[Challenge] Pascal's triangle

### ISSUE THREAD

**Issue by mrumiker** [codeconnector/CodingDojo#283]
# Pascal's triangle

Given an integer `rowCount`, return the first `rowCount` rows of Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it, as shown here:

```
          1
        1   1
      1   2  1
     1  3   3  1
    1  4  6   4  1
```

## Business Rules/Errata

- `rowCount` will be between 1 and 30, inclusive.
- Your function should return a two dimensional array (or your language's equivalent) where each inner array represents a row of Pascal's triangle. The rows should be in the correct order, as should the numbers within each row.

### Example 1:
```
Input: rowCount = 5
Output: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
```

### Example 2:
```
Input: rowCount = 1
Output: [[1]]
```

**Comment by xanderyzwich** [comment]
This one looks good. I'd want to fill the gaps and have tests for rows 2-4 as well.
