### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/CodingDojo#3]
We need to decide on a directory structure. There is a proposal by @drkennetz that we separate challenges from solutions

from Slack

Format could be:
```
./CodingDojo/questions/
    ./03-26-2021/question.MD
    ./04-02-2021/question.MD./CodingDojo/answers/
    ./03-26-2021/answer.py, answer.js, answer.java, answer.rb
./CodingDojo/answers/
    ./03-26-2021/answer.py, answer.js, answer.java, answer.rb
```
(edited to properly display format)

**Comment by xanderyzwich** [comment]
There have been other ideas

Challenges directory could hold README.md of current challenge and then be moved into the directory before solutions are to be accepted.

Challenges could be broken down into data structure and algorithm types or at least named to reflect what they are instead of just dates.

Design challenges could also be included which would nest the above suggestion to have directories in root for `coding` and `design` which would then be broken down similarly as above.

**Comment by parhaml** [comment]
Having just `answer.py` and the like may become problematic.

I think perhaps the answer format should be `githubuser_date_solution.extension`

Eg:

`parhaml_03-26-2021_solution.rb`

**Comment by drkennetz** [comment]
I like the idea @xanderyzwich proposed better than my initial thought. Initially, I was thinking it would be hard to tell what projects were completed without dating them, but fundamentally everything posted should be completed weekly, so lets scratch my idea.

**Comment by birenderjit** [comment]
Is the idea to have everyone's code in the same place or use this more like a place for the optimal solution. So that say I solve it in python and my personal solution could be in my cloned project. However my solution may not be the optimal solution, so should my solution still be in the answers folder. 
Just some thoughts.

**Comment by xanderyzwich** [comment]
@birenderjit we can have several solutions. naming them with username.lang would help. A python solution by me would be xanderyzwich.py and it would be in the solutions directory.

**Comment by xanderyzwich** [comment]
I'm thinking perhaps 

Code Dojo/
    Challenges/
        combine-alternating-lists/
            challenge.md
            solutions/
                xanderywich.py

**Comment by ericwburden** [comment]
I like that, the only change I would make is to incorporate the date into the name of the challenge, so:

```
Code Dojo/
    Challenges/
        2021-03-26-combine-alternating-lists/
            challenge.md
            solutions/
                xanderywich.py
```

Since we're planning to rotate who posts the challenges, this will make it easier to scan recent challenges to confirm you're not doing something very similar to something that was done recently.

**Comment by birenderjit** [comment]
I like @ericwburden's idea to include the date.

**Comment by ericwburden** [comment]
With our first meetup out of the way, I think this issue should be considered resolved.

**Comment by drkennetz** [comment]
I think this can be successfully closed
