### ISSUE TITLE
[Challenge] Two Sum Numbers

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#315]
# Title

Given a list of numbers and a number `k`, return whether any two numbers from the list add up to `k`.

## Business Rules/Errata

- Numbers may be positive or negative.
- The list of numbers may contain fewer than two numbers, in which case your function should return `false`.
- **Bonus Challenge**: Identify the efficiency (time and memory) of your solution. Can you do better?

## Examples

```
two_number_sum(17, &[10, 15, 3, 7])  // true
two_number_sum(17, &[10, 15, 3, 8])  // false
two_number_sum(16, &[10, 15, 8, 7])  // false
two_number_sum(16, &[10, 15, 8, 8])  // true
two_number_sum(32, &[])              // false
two_number_sum(32, &[32])            // false
two_number_sum(32, &[32, 0])         // true
two_number_sum(-32, &[32, 0])        // false
two_number_sum(-32, &[32, -64])      // true
```

**Comment by xanderyzwich** [comment]
closed by #316
