### ISSUE TITLE
[Hacktoberfest] Java | Sum of Squares

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#348]
# Participation

All Hacktoberfest solutions should be provably correct. That is, solution submissions should either include the unit tests from the original challenge (implemented in your language of choice) or at least print out the expected answers when run by the maintainers. Solutions that do not meet these criteria may be rejected, or flagged as 'invalid' or 'spam' in egregious cases. This can result in your PR not counting towards your Hacktoberfest participation or becoming ineligible to participate in Hacktoberfest. Violations of our [Code of Conduct](https://github.com/codeconnector/CodingDojo/blob/main/CODE_OF_CONDUCT.md) will be reported, and will also render you ineligible to participate in Hacktoberfest. Please be respectful of the maintainers' and other participants' time by doing your best to submit real solutions to the puzzles. Thanks, and welcome to our learning community!

# Challenge

[Sum of Squares](https://github.com/codeconnector/CodingDojo/blob/main/challenges/2021-05-18-sum-of-squares/challenge.md)

# Language

Java

# Approach

Check out some of our Java-based challenges for an IDE-agnostic unit-testing setup, or use the tools built in to your favorite IDE.

**Comment by divyansh-ag-03** [comment]
Hi am new to open source, and wanted to give my request for the sum of squares problem. What exactly do you like me to do?

**Comment by ericwburden** [comment]
Welcome to Code Connector! This repo is connected to our Coding Dojo series of meetups, where we practice solving coding puzzles and working through logic live. For this issue, we're providing folks an opportunity to participate in Hacktoberfest by contributing a Java solution to the challenge linked. I recommend reading through the README and repo Wiki for instructions on how to contribute. If you're looking for some direction on contributing to Open Source in general, GitHub has a really good primer on the subject: https://docs.github.com/en/get-started/quickstart/github-flow

**Comment by divyansh-ag-03** [comment]
I have gone through the documentation and I feel I will be able to work on it. Kindly assign this to me.

**Comment by divyansh-ag-03** [comment]
Will give my pr soon, thanks. Am on it.

**Comment by divyansh-ag-03** [comment]
Hi @ericwburden in which directory do you want me to do the work? Is there any specific naming convention for the remote branch or folder?

**Comment by drkennetz** [comment]
Hi @divyansh-ag-03 the solution should go in:
```
challenges/2021-05-18-sum-of-squares/solutions/java/divyansh-ag-03/divyansh-ag-03.java
```
That is our convention. You can instead launch the PR, and we will review the code / request changes there if anything arises.

**Comment by divyansh-ag-03** [comment]
Sure, will change the work directory and launch the pr.
I can't have my Java class name as divyansh-ag-03 as java classes can't have '-' in their names as per convention.

**Comment by divyansh-ag-03** [comment]
Hi, @ericwburden @drkennetz  I have launched a PR with the filename 'divyanshAg03.java', Please have a look at it and let me know if any changes to be made or anything else.
Thanks and Regards 
Divyansh
