### ISSUE TITLE
Weekly Flow

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/CodingDojo#4]
Discussion has been going around as to how we handle the flow of week to week tasks in preparation for the next mob session.

## Challenges 

Challenges will be submitted as issues. Voting on these (👍) should be restricted to one vote per person each week. 

Challenge will be posted on Friday (Monday may be tried as well) for the following week. 

## Solutions
+ No solutions will be accepted  in PR before the mob/meetup. 
+ The mob solution will be titled mob.[lang] in the solutions directory for that challenge. 
+ Solutions may be submitted by anyone after that solution is merged. Any and all solutions of this type will be named with the person's github username and the lang. My solutions will be submitted as xanderyzwich.py if they are in Python. These solutions will be submitted through Pull Request (PR) from the persons fork of the repository. Code reviewers can/will assist with forming the solution such that it can be understood by others and be displayed for learning purposes.

**Comment by ericwburden** [comment]
This seems like exactly the sort of thing that should live in a project wiki. Anybody know how to get that started?

**Comment by birenderjit** [comment]
https://github.com/codeconnector/CodingDojo/wiki

Just created this as a test. We can change/edit this page as we need.

**Comment by ericwburden** [comment]
I like it. I'll add a section on the weekly flow

**Comment by xanderyzwich** [comment]
The intention of this issue has been resolved with the wiki page added in the above link
