### ISSUE TITLE
[Challenge] Sum Arrays

### ISSUE THREAD

**Issue by parhaml** [codeconnector/CodingDojo#47]
# Sum Arrays

Given an array of values, return the sum of the values.
## Business Rules/Errata

- Input must be an array.
- The array may be nested more than one level.
- All values must be integers.
- Solutions shall not use built in methods to flatten the array to one-dimension.

## Examples

One dimension:
```
sum_of_array([1,2,3,4,5]) => 15
```

Two dimensions:
```
sum_of_array([1,2,[1,2,3],4,5]) => 18
```

n dimensions: 

```
sum_of_array([1,[1,2,[3,4],5],[6,7]]) => 29
```

**Comment by ericwburden** [comment]
Ah man, this one is really hard! (Assuming you use a statically typed language that doesn't natively support arbitrarily nested arrays).

**Comment by parhaml** [comment]
> Ah man, this one is really hard! (Assuming you use a statically typed language that doesn't natively support arbitrarily nested arrays).

That's an interesting point. Perhaps it's for later or for a subset of languages.

**Comment by parhaml** [comment]
It should be fun!
