### ISSUE TITLE
[Challenge] A Box in a Box

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#53]
# A Box in a Box

Given a pair of rectangles, determine whether one of the rectangles is completely contained within the other rectangle. You will be given each rectangles top-left coordinate in an x/y plane, the rectangle's width, and the rectangle's height. One rectangle is "completely contained" by a rectangle that completely covers it, if viewed from above the plane. This puzzle should be solved using an Object-Oriented approach.

## Business Rules/Errata

- ***Data Structure Required: Rectangle*** You should produce and compare `Rectangle` objects in your solution, not the raw rectangle measurements.
- The rectangle dimensions will be given in an array, in the format [(top left x coordinate), (top left y coordinate), (width), (height)].
- The units of width and height are irrelevant and can be ignored.
- **The coordinate system for this challenge is 2-dimensional, with x increasing from left to right, and y increasing from top to bottom.**
- Your final result should include a function that, given two sets of rectangle dimensions, returns a boolean value,
- Your function should return `false` if the two rectangles only partially overlap.

### Example 1

```
rectangle1 = [1, 4, 3, 3]
rectangle2 = [0, 3, 2, 1]
rectanglesOverlap(rectangle1, rectangle2)  // false
```

![image](https://user-images.githubusercontent.com/22438085/116640185-eb3afa00-a92f-11eb-9c74-281cde7c2832.png)

### Example 2

```
rectangle1 = [1, 4, 3, 3]
rectangle2 = [0, 3, 4, 4]
rectanglesOverlap(rectangle1, rectangle2)  // true
```

![image](https://user-images.githubusercontent.com/22438085/116640295-2f2dff00-a930-11eb-9f5d-4360b297d7ac.png)

### Example 3

```
rectangle1 = [1, 4, 3, 3]
rectangle2 = [0, 3, 3, 3]
rectanglesOverlap(rectangle1, rectangle2)  // false
```

![image](https://user-images.githubusercontent.com/22438085/116640512-68ff0580-a930-11eb-95ef-623834156c17.png)

**Comment by xanderyzwich** [comment]
This one seems straight forward with enough edge/corner (pun intended) cases to be interesting.

**Comment by drkennetz** [comment]
This one seems fun
