### ISSUE TITLE
[Challenge] Coin Counter

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#55]
# Coin Counter

You are given `n` fair coins, and you flip all at the same time. Every time a coin comes up 'tails', it is removed from play. The ones that come up 'heads', you will flip again on the next round. Write a function that, given `n`, returns the number of rounds you'd expect to play until only one coin remains.

## Business Rules/Errata

- Each coin is fair, meaning it is equally likely to come up as either side on any given round.
- Your answer should be rounded to the nearest whole number, since it is impossible to play part of a round.
- Extra Challenge: What is the most time-efficient solution you can devise?
- Extra Challenge: Can you implement this game for dice, instead of coins?

## Examples

```
count_coin_rounds(2)        // 1
count_coin_rounds(100)    // 7
count_coin_rounds(1000)  // 10
```

**Comment by ericwburden** [comment]
Math, amirite?

**Comment by xanderyzwich** [comment]
Yeah. This is a classic example where you don't HAVE TO know math to write code, but it could make things a lot easier.
