### ISSUE TITLE
[Challenge] Limited Levenshtein Leap

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#56]
# Limited Levenshtein Leap

Given a `start` word, and `end` word, and a "dictionary" of valid words, find the shortest transformation sequence from `start` to `end` such that only one letter is changed at each step of the sequence, and each transformed word exists in the dictionary. If there is no possible transformation, return NULL.

## Business Rules/Errata

- The "dictionary" is simply an unordered array of strings.
- The `start`, `stop`, and "dictionary" words will all be the same length and all lowercase.
- Your function should return the sequence of words that represent the transformations from start to end.

### Example 1

```
start = "dog"
end = "cat"
dictionary = ["dot", "dop", "dat", "cat"]
findTransformSequence(start, end, dictionary)  // ["dog", "dot", "dat", "cat"]
```

### Example 2

```
start = "dog"
end = "cat"
dictionary = ["dot", "tod", "dat", "dar"]
findTransformSequence(start, end, dictionary)  // NULL
```

**Comment by xanderyzwich** [comment]
I really like this one, but I know that it might get into the weeds along the way unless we keep the test dictionaries short.

Conversely I feel like if we don't have wrong turns to be checked then the implementation won't be complete.
