### ISSUE TITLE
[Challenge] Use a debugger

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/CodingDojo#67]
# Use a debugger

the Challenge setup will require some nearly complete broken bits of code

## Business Rules/Errata

+ Language agnostic (although the setup will require knowledge beforehand)

## Examples

Can reuse a previous challenge that is sufficiently complex to have multiple functions that may need troubleshooting.

**Comment by ericwburden** [comment]
Recommend closing this issue, we've settled on proposing this for another meetup as a collaboration!
