### ISSUE TITLE
[Challenge] Square Maze

### ISSUE THREAD

**Issue by ericwburden** [codeconnector/CodingDojo#9]
# Square Maze

Given a square (NxN) matrix of '0's and '1's, determine how many ways the matrix can be traversed from the top left element to the bottom right element.

## Business Rules/Errata

- ***Data Structure Required: 2D Matrix***
- Assume the matrix represents a 2-dimensional map.
- You may only move up, down, left, and right in the matrix, not diagonally.
- You may only traverse matrix elements that are '0' (representing an empty space). A '1' represents an impassible barrier.
- The top left and bottom right corner will always be '0'.
- If there is no path from the top left to the bottom right, return 0. Otherwise, return the number of viable paths as an integer.

## Examples

```
input = [[0, 0, 1],
         [0, 0, 1],
         [1, 0, 0]]

count_paths(input)  // 2
```
In this case, there are two viable paths, starting at the top left:

- right, down, down, right
- down, right, down, right

**Comment by beccani** [comment]
This one seems cool!!
